version: "3.9"

services:
  spring:
    container_name: spring
    platform: linux/amd64
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      MYSQL_USERNAME: admin
      MYSQL_PASSWORD: admin
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    networks:
      - local

  mysql:
    container_name: mysql
    image: mysql:8.0
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: admin
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: admin
    volumes:
      - ~/volume_name/mysql:/var/lib/mysql
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    networks:
      - local

networks:
  local:
    driver: bridge