spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/admin?serverTimezone=Asia/Seoul
    username: admin
    password: Admin1234!!
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

  security:
    oauth2:
      client:
        registration:
          kakao-login:
            client-name: kakao
            client-id: 7e558adbc7b32496ba547bfbbaa19261
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope:
              - account_email

        provider:
          kakao-login:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

auth:
  kakao:
    secret: secret

  jwt:
    secret: gewGE454568GYhiolLO2465TFY5215kFF45258YYhiolLO2465TFY2049gewGE454568GYhiolLO2465TFY5215kFF45258YYhiolLO2465TFY2049gewGE454568GYhiolLO2465TFY5215kFF45258YYhiolLO2465TFY2049gewGE454568GYhiolLO2465TFY5215kFF45258YYhiolLO2465TFY2049gewGE454568GYhiolLO2465TFY5215kFF45258YYhiolLO2465TFY2049gewGE454568GYhiolLO2465TFY5215kFF45258YYhiolLO2465TFY2049
    expires: 180000